/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openkinect_Context */

#ifndef _Included_org_openkinect_Context
#define _Included_org_openkinect_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_openkinect_Context
 * Method:    jniInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_openkinect_Context_jniInit
  (JNIEnv *, jobject);

/*
 * Class:     org_openkinect_Context
 * Method:    jniShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_openkinect_Context_jniShutdown
  (JNIEnv *, jobject);

/*
 * Class:     org_openkinect_Context
 * Method:    jniProcessEvents
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_openkinect_Context_jniProcessEvents
  (JNIEnv *, jobject);

/*
 * Class:     org_openkinect_Context
 * Method:    jniNumDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openkinect_Context_jniNumDevices
  (JNIEnv *, jobject);

/*
 * Class:     org_openkinect_Context
 * Method:    jniOpenDevice
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_openkinect_Context_jniOpenDevice
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openkinect_Context
 * Method:    jniSetLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openkinect_Context_jniSetLogLevel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
