.TH FAKENECT 1 2012-01-29 "libfreenect" "libfreenect manual"
.SH NAME
fakenect - Run a program by faking the Kinect
.SH SYNOPSIS
.SY fakenect 
.I database
.I application
.I args
.br
.SH DESCRIPTION
.LP
\fBfakenect\fP runs \fIapplication\fP with the arguments \fIargs\fP using
the data contained in the folder \fIdatabase\fP. These data should have been
recorded using \fIfakenect-record\fP(1).
.SH "SEE ALSO"
.BR fakenect-record (1)


